services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: frontend-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge