{
 "title": "MySQL Monitoring Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "node_load1" }
  ]
 },
 "panels": [
  {
   "title": "Uptime (SG)",
   "type": "stat",
   "description": "**Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{job=\"mysqld_exporter_sg\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_running"
    }
   ]
  },
  {
   "title": "MySQL Logs Denmark",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"mysql-denmark\"} |= ``"
    }
   ]
  },
  {
   "title": "Uptime (Denmark)",
   "type": "stat",
   "description": "**Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{job=\"mysqld_exporter_denmark\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_connections",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_global_status_queries" }
   ]
  },
  {
   "title": "MySQL Logs SG",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{container_name=\"mysql-sg\"} |= ``"
    }
   ]
  },
  {
   "title": "Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_questions[5m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}